#!/bin/bash
#
DIR=${PWD}
git rev-parse --is-inside-work-tree > /dev/null 2>&1
GIT_CHECK=$?
if [ GIT_CHECK -eq 0 ]; then
	echo "This is not a valid git repo! Exiting..."
	exit 1
fi
MASTER_BR=$(git config --get gitflow.branch.master)
DEV_BR=$(git config --get gitflow.branch.develop)
if [[ -z $MASTER_BR ]]; then
	echo "MASTER BRANCH not set. Use 'git flow init' command to initalize git flow";
	exit 2
fi
if [[ -z $DEV_BR ]]; then
	echo "DEVELOPMENT BRANCH not set. Use 'git flow init' command to initalize git flow";
	exit 3
fi
set -e
echo "FETCHING LATEST"
git fetch --prune --all --progress
echo "$MASTER_BR PULL"
git checkout $MASTER_BR
git merge
echo "$DEV_BR PULL"
git checkout $DEV_BR
git merge
echo "=== DONE ==="
